(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<< "/Users/oliviercroissant/Documents/Math/NumericalIntegration.m"


<< "/Users/oliviercroissant/Documents/Math/My Documents\\BS.m"


<< "/Users/oliviercroissant/Documents/Math/Heston_Definitif5.m"


Needs["PlotLegends`"]


BiHestonVanilla[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,\[Beta]_,\[Rho]_,printflag_]:=Module[{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,LegendreCoef2,period2,period2n,\[Epsilon]2,imax,\[Lambda]1,\[Lambda]2,Q},
Q=CholeskyDecomposition[-((M.\[CapitalSigma]inf+\[CapitalSigma]inf. Transpose[M])/2)]/\[Beta];
{{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1},{LegendreCoef2,period2,period2n,\[Epsilon]2},imax,\[Lambda]1,\[Lambda]2}=BiHestonVanillaOptimalParameters[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],"VanillaSpreadoption"];
BiHestonVanilla[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag]
]


BiHestonVanilla2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,printflag_]:=Module[{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,LegendreCoef2,period2,period2n,\[Epsilon]2,imax,\[Lambda]1,\[Lambda]2,\[Beta]m},
{{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1},{LegendreCoef2,period2,period2n,\[Epsilon]2},imax,\[Lambda]1,\[Lambda]2}=BiHestonVanillaOptimalParameters[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],"VanillaSpreadoption"];
\[Beta]m=-((M.\[CapitalSigma]inf+\[CapitalSigma]inf.Transpose[M])/2).Inverse[(Transpose[Q].Q)];
BiHestonVanilla2[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag]
]


BiHestonVanilla[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=BiHestonVanillaAux[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag] /; K>=0


BiHestonVanilla[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=BiHestonVanillaAux[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag]+S[[1]]-S[[2]]-K/; K<0


BiHestonVanilla2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=BiHestonVanillaAux2[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag] /; K>=0


BiHestonVanilla2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=BiHestonVanillaAux2[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag]+S[[1]]-S[[2]]-K/; K<0


BiHestonVanillaAux[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=
2/(2\[Pi])^2 Module[{a,res,res2,Y={Log[S[[1]]],Log[S[[2]]]}},
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",S // ColumnForm," \[CapitalSigma]=",\[CapitalSigma] //MatrixForm,"M=",M//MatrixForm," \[CapitalSigma]inf=",\[CapitalSigma]inf//MatrixForm ," Q=",Q//MatrixForm ," \[Rho]=",\[Rho]//ColumnForm," Imaginary Shifts=",{\[Lambda]1,\[Lambda]2} // ColumnForm];
Print["{NbLegCoef1,NbLegCoef1n,period1,period1n,\[Epsilon]1,imax}=",{Length[LegendreCoef1],Length[LegendreCoef1n],period1,period1n,\[Epsilon]1,imax},"{NbLegCoef2,period2,period2n,\[Epsilon]2}=",{Length[LegendreCoef2],period2,period2n,\[Epsilon]2}]];
If[printflag==4|| MemberQ[printflag,4] ,Print[Table[Plot[SymetrizedBiHestonVanillaIntegrand[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2],{\[Omega]2,0 ,2period2},PlotPoints->50,PlotRange->All,PlotLabel->"1st Inverse Fourier: K ="<>ToString[K]<>" \[Omega]1="<>ToString[\[Omega]1]],{\[Omega]1,{0,0.2,2}}]]];
If[printflag==6|| MemberQ[printflag,6] ,Print[ListPlot[Table[{\[Omega]2,AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonVanillaIntegrand[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax][[2]]},{\[Omega]2,0,period2,period2/30}],Joined->True,PlotLabel->"2nd Inverse Fourier:",PlotRange->All]]];
res=AdaptativeIntegrate[Function[\[Omega]2,a=AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonVanillaIntegrand[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax];If[printflag==7|| MemberQ[printflag,7],Print["Integ_2=",a]];a[[2]]],LegendreCoef2,period2,period2n,\[Epsilon]2,imax];
If[printflag==7|| MemberQ[printflag,7],Print["Integ_1=",res]];
res[[2]]]


BiHestonVanillaAux2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=
2/(2\[Pi])^2 Module[{a,res,res2,Y={Log[S[[1]]],Log[S[[2]]]}},
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",S // ColumnForm," \[CapitalSigma]=",\[CapitalSigma] //MatrixForm,"M=",M//MatrixForm," \[CapitalSigma]inf=",\[CapitalSigma]inf//MatrixForm ," Q=",Q//MatrixForm ," \[Rho]=",\[Rho]//ColumnForm," Imaginary Shifts=",{\[Lambda]1,\[Lambda]2} // ColumnForm];
Print["{NbLegCoef1,NbLegCoef1n,period1,period1n,\[Epsilon]1,imax}=",{Length[LegendreCoef1],Length[LegendreCoef1n],period1,period1n,\[Epsilon]1,imax},"{NbLegCoef2,period2,period2n,\[Epsilon]2}=",{Length[LegendreCoef2],period2,period2n,\[Epsilon]2}]];
If[printflag==4|| MemberQ[printflag,4] ,Print[Table[Plot[SymetrizedBiHestonVanillaIntegrand2[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2],{\[Omega]2,0 ,2period2},PlotPoints->50,PlotRange->All,PlotLabel->"1st Inverse Fourier: K ="<>ToString[K]<>" \[Omega]1="<>ToString[\[Omega]1]],{\[Omega]1,{0,0.2,2}}]]];
If[printflag==6|| MemberQ[printflag,6] ,Print[ListPlot[Table[{\[Omega]2,AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonVanillaIntegrand2[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax][[2]]},{\[Omega]2,0,period2,period2/30}],Joined->True,PlotLabel->"2nd Inverse Fourier:",PlotRange->All]]];
res=AdaptativeIntegrate[Function[\[Omega]2,a=AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonVanillaIntegrand2[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax];If[printflag==2,Print["Integ_2=",a]];a[[2]]],LegendreCoef2,period2,period2n,\[Epsilon]2,imax];
If[printflag==2,Print["Integ_1=",res]];
res[[2]]]


SymetrizedBiHestonVanillaIntegrand[Y_,K_,\[Tau]_,\[CapitalSigma]_,M_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,\[Omega]1_,\[Omega]2_]:=Module[{x1=Y[[1]],x2=Y[[2]],k1=(\[Omega]1+I \[Lambda]1),Sk1=(-\[Omega]1+I \[Lambda]1),k2= (\[Omega]2+I \[Lambda]2),Sk2= (-\[Omega]2+I \[Lambda]2),Sk1A=(-\[Omega]1+I \[Lambda]1),k1A=(\[Omega]1-I \[Lambda]1),k2A=(\[Omega]2-I \[Lambda]2),\[Alpha],\[Alpha]A,Sym\[Alpha],Sym\[Alpha]A,\[Alpha]2,\[Alpha]A2,Sym\[Alpha]2,Sym\[Alpha]A2,propagatorDroit,SympropagatorDroit,propagatorGauche,SympropagatorGauche,propagatorDroit2,SympropagatorDroit2,propagatorGauche2,SympropagatorGauche2},
Re[If[K>0,
\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);
propagatorDroit=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta],\[Tau]];SympropagatorDroit=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta],\[Tau]];
propagatorGauche=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2A},\[Beta],\[Tau]];SympropagatorGauche=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta],\[Tau]];
\[Alpha] propagatorDroit VanillaPayOffFourierDroite[k1,k2,K]+
Sym\[Alpha] SympropagatorDroit VanillaPayOffFourierDroite[Sk1,k2,K]+
\[Alpha]A propagatorGauche VanillaPayOffFourierGauche[k1,k2A,K]+
Sym\[Alpha]A SympropagatorGauche VanillaPayOffFourierGauche[Sk1A,k2A,K],
If[K<0,
\[Alpha]2=E^(-I x2 k1-I x1 k2);\[Alpha]A2=E^(-I x2 k1-I x1 k2A);Sym\[Alpha]2=E^(-I x2 Sk1-I x1 k2);Sym\[Alpha]A2=E^(-I x2 Sk1A-I x1 k2A);
propagatorDroit2=BiHestonLaplaceQuickTransformReverse[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta],\[Tau]];SympropagatorDroit2=BiHestonLaplaceQuickTransformReverse[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta],\[Tau]];
propagatorGauche2=BiHestonLaplaceQuickTransformReverse[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2A},\[Beta],\[Tau]];SympropagatorGauche2=BiHestonLaplaceQuickTransformReverse[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta],\[Tau]];(\[Alpha]2 (propagatorDroit2 (VanillaPayOffFourierDroite[k1,k2,-K]))+Sym\[Alpha]2 (SympropagatorDroit2 (VanillaPayOffFourierDroite[Sk1,k2,-K]))) +
(\[Alpha]A2 propagatorGauche2 ( VanillaPayOffFourierGauche[k1,k2A,-K])+Sym\[Alpha]A2 SympropagatorGauche2 (VanillaPayOffFourierGauche[Sk1A,k2A,-K]))
,
\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);
propagatorDroit=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta],\[Tau]];SympropagatorDroit=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta],\[Tau]];
propagatorGauche=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2A},\[Beta],\[Tau]];SympropagatorGauche=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta],\[Tau]];
\[Alpha] propagatorDroit VanillaPayOffFourierDroite[k1,k2]+
Sym\[Alpha] SympropagatorDroit VanillaPayOffFourierDroite[Sk1,k2]+
\[Alpha]A propagatorGauche VanillaPayOffFourierGauche[k1,k2A]+
Sym\[Alpha]A SympropagatorGauche VanillaPayOffFourierGauche[Sk1,k2A]]]]]


SymetrizedBiHestonVanillaIntegrand2[Y_,K_,\[Tau]_,\[CapitalSigma]_,M_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,\[Omega]1_,\[Omega]2_]:=Module[{x1=Y[[1]],x2=Y[[2]],k1=(\[Omega]1+I \[Lambda]1),Sk1=(-\[Omega]1+I \[Lambda]1),k2= (\[Omega]2+I \[Lambda]2),Sk2= (-\[Omega]2+I \[Lambda]2),Sk1A=(-\[Omega]1+I \[Lambda]1),k1A=(\[Omega]1-I \[Lambda]1),k2A=(\[Omega]2-I \[Lambda]2),\[Alpha],\[Alpha]A,Sym\[Alpha],Sym\[Alpha]A,\[Alpha]2,\[Alpha]A2,Sym\[Alpha]2,Sym\[Alpha]A2,propagatorDroit,SympropagatorDroit,propagatorGauche,SympropagatorGauche,propagatorDroit2,SympropagatorDroit2,propagatorGauche2,SympropagatorGauche2},
Re[If[K>0,
\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);
propagatorDroit=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta]m,\[Tau]];SympropagatorDroit=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta]m,\[Tau]];
propagatorGauche=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2A},\[Beta]m,\[Tau]];SympropagatorGauche=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta]m,\[Tau]];
\[Alpha] propagatorDroit VanillaPayOffFourierDroite[k1,k2,K]+
Sym\[Alpha] SympropagatorDroit VanillaPayOffFourierDroite[Sk1,k2,K]+
\[Alpha]A propagatorGauche VanillaPayOffFourierGauche[k1,k2A,K]+
Sym\[Alpha]A SympropagatorGauche VanillaPayOffFourierGauche[Sk1A,k2A,K],
If[K<0,
\[Alpha]2=E^(-I x2 k1-I x1 k2);\[Alpha]A2=E^(-I x2 k1-I x1 k2A);Sym\[Alpha]2=E^(-I x2 Sk1-I x1 k2);Sym\[Alpha]A2=E^(-I x2 Sk1A-I x1 k2A);
propagatorDroit2=BiHestonLaplaceQuickTransformReverse2[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta]m,\[Tau]];SympropagatorDroit2=BiHestonLaplaceQuickTransformReverse2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta]m,\[Tau]];
propagatorGauche2=BiHestonLaplaceQuickTransformReverse2[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2A},\[Beta]m,\[Tau]];SympropagatorGauche2=BiHestonLaplaceQuickTransformReverse2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta]m,\[Tau]];(\[Alpha]2 (propagatorDroit2 (VanillaPayOffFourierDroite[k1,k2,-K]))+Sym\[Alpha]2 (SympropagatorDroit2 (VanillaPayOffFourierDroite[Sk1,k2,-K]))) +
(\[Alpha]A2 propagatorGauche2 ( VanillaPayOffFourierGauche[k1,k2A,-K])+Sym\[Alpha]A2 SympropagatorGauche2 (VanillaPayOffFourierGauche[Sk1A,k2A,-K]))
,
\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);
propagatorDroit=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta]m,\[Tau]];SympropagatorDroit=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta]m,\[Tau]];
propagatorGauche=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2A},\[Beta]m,\[Tau]];SympropagatorGauche=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta]m,\[Tau]];
\[Alpha] propagatorDroit VanillaPayOffFourierDroite[k1,k2]+
Sym\[Alpha] SympropagatorDroit VanillaPayOffFourierDroite[Sk1,k2]+
\[Alpha]A propagatorGauche VanillaPayOffFourierGauche[k1,k2A]+
Sym\[Alpha]A SympropagatorGauche VanillaPayOffFourierGauche[Sk1,k2A]]]]]


BiHestonLaplaceQuickTransform[{{M11_,M12_},{M21_,M22_}},{{Q11_,Q12_},{Q21_,Q22_}},{\[Rho]1_,\[Rho]2_},{{\[CapitalSigma]11_,\[CapitalSigma]12_},{\[CapitalSigma]21_,\[CapitalSigma]22_}},{\[Gamma]1_,\[Gamma]2_},\[Beta]_,\[Tau]_]:=
Module[{EXPH=MatrixExp[\[Tau] {{1/2 (-M11-Q11 \[Gamma]1 \[Rho]1-Q21 \[Gamma]1 \[Rho]2),1/2 (-M12-Q11 \[Gamma]2 \[Rho]1-Q21 \[Gamma]2 \[Rho]2),1/2 (-Q11^2-Q21^2),1/2 (-Q11 Q12-Q21 Q22)},{1/2 (-M21-Q12 \[Gamma]1 \[Rho]1-Q22 \[Gamma]1 \[Rho]2),1/2 (-M22-Q12 \[Gamma]2 \[Rho]1-Q22 \[Gamma]2 \[Rho]2),1/2 (-Q11 Q12-Q21 Q22),1/2 (-Q12^2-Q22^2)},{1/2 (-1+\[Gamma]1) \[Gamma]1,(\[Gamma]1 \[Gamma]2)/2,1/2 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2),1/2 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)},{(\[Gamma]1 \[Gamma]2)/2,1/2 (-1+\[Gamma]2) \[Gamma]2,1/2 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2),1/2 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)}}],\[Delta]},
\[Delta]=-EXPH[[1,2]] EXPH[[2,1]]+EXPH[[1,1]] EXPH[[2,2]];
Exp[1/\[Delta] (EXPH[[2,2]] EXPH[[3,1]] \[CapitalSigma]11-EXPH[[1,2]] EXPH[[4,1]] \[CapitalSigma]11-EXPH[[2,1]] EXPH[[3,1]] \[CapitalSigma]12+EXPH[[2,2]] EXPH[[3,2]] \[CapitalSigma]12+
EXPH[[1,1]] EXPH[[4,1]] \[CapitalSigma]12-EXPH[[1,2]] EXPH[[4,2]] \[CapitalSigma]12-EXPH[[2,1]] EXPH[[3,2]] \[CapitalSigma]22+EXPH[[1,1]] EXPH[[4,2]] \[CapitalSigma]22)-2\[Beta]^2 (Log[\[Delta]]+\[Tau]/2 ( M11+M22+Q11 \[Gamma]1 \[Rho]1+Q12 \[Gamma]2 \[Rho]1+Q21 \[Gamma]1 \[Rho]2+Q22 \[Gamma]2 \[Rho]2))]
]


BiHestonLaplaceQuickTransform2[{{M11_,M12_},{M21_,M22_}},{{Q11_,Q12_},{Q21_,Q22_}},{\[Rho]1_,\[Rho]2_},{{\[CapitalSigma]11_,\[CapitalSigma]12_},{\[CapitalSigma]21_,\[CapitalSigma]22_}},{\[Gamma]1_,\[Gamma]2_},{{\[Beta]11_,\[Beta]12_},{\[Beta]21_,\[Beta]22_}},\[Tau]_]:=
Module[{EXPH=MatrixExp[\[Tau] {{1/2 (-M11-Q11 \[Gamma]1 \[Rho]1-Q21 \[Gamma]1 \[Rho]2),1/2 (-M12-Q11 \[Gamma]2 \[Rho]1-Q21 \[Gamma]2 \[Rho]2),1/2 (-Q11^2-Q21^2),1/2 (-Q11 Q12-Q21 Q22)},{1/2 (-M21-Q12 \[Gamma]1 \[Rho]1-Q22 \[Gamma]1 \[Rho]2),1/2 (-M22-Q12 \[Gamma]2 \[Rho]1-Q22 \[Gamma]2 \[Rho]2),1/2 (-Q11 Q12-Q21 Q22),1/2 (-Q12^2-Q22^2)},{1/2 (-1+\[Gamma]1) \[Gamma]1,(\[Gamma]1 \[Gamma]2)/2,1/2 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2),1/2 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)},{(\[Gamma]1 \[Gamma]2)/2,1/2 (-1+\[Gamma]2) \[Gamma]2,1/2 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2),1/2 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)}}],\[Delta],LogA11},
\[Delta]=-EXPH[[1,2]] EXPH[[2,1]]+EXPH[[1,1]] EXPH[[2,2]];
LogA11=MatrixLog2[{{EXPH[[1,1]],EXPH[[1,2]]},{EXPH[[2,1]],EXPH[[2,2]]}}];
Exp[1/\[Delta] (EXPH[[2,2]] EXPH[[3,1]] \[CapitalSigma]11-EXPH[[1,2]] EXPH[[4,1]] \[CapitalSigma]11-EXPH[[2,1]] EXPH[[3,1]] \[CapitalSigma]12+EXPH[[2,2]] EXPH[[3,2]] \[CapitalSigma]12+
EXPH[[1,1]] EXPH[[4,1]] \[CapitalSigma]12-EXPH[[1,2]] EXPH[[4,2]] \[CapitalSigma]12-EXPH[[2,1]] EXPH[[3,2]] \[CapitalSigma]22+EXPH[[1,1]] EXPH[[4,2]] \[CapitalSigma]22)-2(\[Beta]11 LogA11[[1,1]]+\[Beta]12 LogA11[[1,2]]+\[Beta]21 LogA11[[2,1]]+\[Beta]22 LogA11[[2,2]]+1/2 (\[Beta]11 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2)+\[Beta]21 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)+\[Beta]12 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2)+\[Beta]22 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)) \[Tau])]
]


BiHestonLaplaceQuickTransformReverse[{{M22_,M21_},{M12_,M11_}},{{Q22_,Q21_},{Q12_,Q11_}},{\[Rho]2_,\[Rho]1_},{{\[CapitalSigma]22_,\[CapitalSigma]21_},{\[CapitalSigma]12_,\[CapitalSigma]11_}},{\[Gamma]1_,\[Gamma]2_},\[Beta]_,\[Tau]_]:=
Module[{EXPH=MatrixExp[\[Tau] {{1/2 (-M11-Q11 \[Gamma]1 \[Rho]1-Q21 \[Gamma]1 \[Rho]2),1/2 (-M12-Q11 \[Gamma]2 \[Rho]1-Q21 \[Gamma]2 \[Rho]2),1/2 (-Q11^2-Q21^2),1/2 (-Q11 Q12-Q21 Q22)},{1/2 (-M21-Q12 \[Gamma]1 \[Rho]1-Q22 \[Gamma]1 \[Rho]2),1/2 (-M22-Q12 \[Gamma]2 \[Rho]1-Q22 \[Gamma]2 \[Rho]2),1/2 (-Q11 Q12-Q21 Q22),1/2 (-Q12^2-Q22^2)},{1/2 (-1+\[Gamma]1) \[Gamma]1,(\[Gamma]1 \[Gamma]2)/2,1/2 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2),1/2 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)},{(\[Gamma]1 \[Gamma]2)/2,1/2 (-1+\[Gamma]2) \[Gamma]2,1/2 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2),1/2 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)}}],\[Delta]},
\[Delta]=-EXPH[[1,2]] EXPH[[2,1]]+EXPH[[1,1]] EXPH[[2,2]];
Exp[1/\[Delta] (EXPH[[2,2]] EXPH[[3,1]] \[CapitalSigma]11-EXPH[[1,2]] EXPH[[4,1]] \[CapitalSigma]11-EXPH[[2,1]] EXPH[[3,1]] \[CapitalSigma]12+EXPH[[2,2]] EXPH[[3,2]] \[CapitalSigma]12+
EXPH[[1,1]] EXPH[[4,1]] \[CapitalSigma]12-EXPH[[1,2]] EXPH[[4,2]] \[CapitalSigma]12-EXPH[[2,1]] EXPH[[3,2]] \[CapitalSigma]22+EXPH[[1,1]] EXPH[[4,2]] \[CapitalSigma]22)-2\[Beta]^2 (Log[\[Delta]]+\[Tau]/2 ( M11+M22+Q11 \[Gamma]1 \[Rho]1+Q12 \[Gamma]2 \[Rho]1+Q21 \[Gamma]1 \[Rho]2+Q22 \[Gamma]2 \[Rho]2))]
]


BiHestonLaplaceQuickTransformReverse2[{{M22_,M21_},{M12_,M11_}},{{Q22_,Q21_},{Q12_,Q11_}},{\[Rho]2_,\[Rho]1_},{{\[CapitalSigma]22_,\[CapitalSigma]21_},{\[CapitalSigma]12_,\[CapitalSigma]11_}},{\[Gamma]1_,\[Gamma]2_},{{\[Beta]11_,\[Beta]12_},{\[Beta]21_,\[Beta]22_}},\[Tau]_]:=
Module[{EXPH=MatrixExp[\[Tau] {{1/2 (-M11-Q11 \[Gamma]1 \[Rho]1-Q21 \[Gamma]1 \[Rho]2),1/2 (-M12-Q11 \[Gamma]2 \[Rho]1-Q21 \[Gamma]2 \[Rho]2),1/2 (-Q11^2-Q21^2),1/2 (-Q11 Q12-Q21 Q22)},{1/2 (-M21-Q12 \[Gamma]1 \[Rho]1-Q22 \[Gamma]1 \[Rho]2),1/2 (-M22-Q12 \[Gamma]2 \[Rho]1-Q22 \[Gamma]2 \[Rho]2),1/2 (-Q11 Q12-Q21 Q22),1/2 (-Q12^2-Q22^2)},{1/2 (-1+\[Gamma]1) \[Gamma]1,(\[Gamma]1 \[Gamma]2)/2,1/2 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2),1/2 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)},{(\[Gamma]1 \[Gamma]2)/2,1/2 (-1+\[Gamma]2) \[Gamma]2,1/2 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2),1/2 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)}}],\[Delta],LogA11},
\[Delta]=-EXPH[[1,2]] EXPH[[2,1]]+EXPH[[1,1]] EXPH[[2,2]];
LogA11=MatrixLog2[{{EXPH[[1,1]],EXPH[[1,2]]},{EXPH[[2,1]],EXPH[[2,2]]}}];
Exp[1/\[Delta] (EXPH[[2,2]] EXPH[[3,1]] \[CapitalSigma]11-EXPH[[1,2]] EXPH[[4,1]] \[CapitalSigma]11-EXPH[[2,1]] EXPH[[3,1]] \[CapitalSigma]12+EXPH[[2,2]] EXPH[[3,2]] \[CapitalSigma]12+
EXPH[[1,1]] EXPH[[4,1]] \[CapitalSigma]12-EXPH[[1,2]] EXPH[[4,2]] \[CapitalSigma]12-EXPH[[2,1]] EXPH[[3,2]] \[CapitalSigma]22+EXPH[[1,1]] EXPH[[4,2]] \[CapitalSigma]22)-2(\[Beta]11 LogA11[[1,1]]+\[Beta]12 LogA11[[1,2]]+\[Beta]21 LogA11[[2,1]]+\[Beta]22 LogA11[[2,2]]+1/2 (\[Beta]11 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2)+\[Beta]21 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)+\[Beta]12 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2)+\[Beta]22 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)) \[Tau])]
]


VanillaPayOffFourierDroite[k1_,k2_,K_]:=K^(I k1)/(k1 (-I+k1) k2 (-I+k2)) ( K^(I k2+1)/Gamma[-I k1] ( 
(1+I k2) Gamma[1+I k2] ( Gamma[-I (k1+k2)])+I  k2 Gamma[2+I k2] (  Gamma[-I (-I+k1+k2)]))-
  (I  k2 Hypergeometric2F1[-I k1,1+I k2,2+I k2,-(1/K)]+K (1+I k2) Hypergeometric2F1[-I k1,I k2,1+I k2,-(1/K)]))


VanillaPayOffFourierDroite[k1_,k2_]:=1/(k1 (-I+k1) (1+I k1+I k2))


VanillaPayOffFourierGauche[k1_,k2_,K_]:=K^(I k1)/(k1 (-I+k1) k2 (-I+k2))  (I  k2 Hypergeometric2F1[-I k1,1+I k2,2+I k2,-(1/K)]+K (1+I k2) Hypergeometric2F1[-I k1,I k2,1+I k2,-(1/K)])


VanillaPayOffFourierGauche[k1_,k2_]:=-1/(k1 (-I+k1) (1+I k1+I k2))


BiHestonUnderlying1Vanilla[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,\[Beta]_,\[Rho]_,printflag_]:=Module[{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,LegendreCoef2,period2,period2n,\[Epsilon]2,imax,\[Lambda]1,\[Lambda]2,Q},
Q=CholeskyDecomposition[-((M.\[CapitalSigma]inf+\[CapitalSigma]inf. Transpose[M])/2)]/\[Beta];
{{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1},{LegendreCoef2,period2,period2n,\[Epsilon]2},imax,\[Lambda]1,\[Lambda]2}=BiHestonVanillaOptimalParameters[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],"Underlying1Option"];
BiHestonUnderlying1Vanilla[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag]
]


BiHestonUnderlying1Vanilla2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,printflag_]:=Module[{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,LegendreCoef2,period2,period2n,\[Epsilon]2,imax,\[Lambda]1,\[Lambda]2,\[Beta]m},
{{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1},{LegendreCoef2,period2,period2n,\[Epsilon]2},imax,\[Lambda]1,\[Lambda]2}=BiHestonVanillaOptimalParameters[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],"Underlying1Option"];
\[Beta]m=-((M.\[CapitalSigma]inf+\[CapitalSigma]inf.Transpose[M])/2).Inverse[(Transpose[Q].Q)];
BiHestonUnderlying1Vanilla2[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag]
]


BiHestonUnderlying1Vanilla[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=BiHestonUnderlying1VanillaAux[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag] /; K>=0


BiHestonUnderlying1Vanilla2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=BiHestonUnderlying1VanillaAux2[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag] /; K>=0


BiHestonUnderlying1VanillaAux[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=
2/(2\[Pi])^2 Module[{a,res,res2,Y={Log[S[[1]]],Log[S[[2]]]}},
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",S // ColumnForm," \[CapitalSigma]=",\[CapitalSigma] //MatrixForm,"M=",M//MatrixForm," \[CapitalSigma]inf=",\[CapitalSigma]inf//MatrixForm ," Q=",Q//MatrixForm ," \[Rho]=",\[Rho]//ColumnForm," Imaginary Shifts=",{\[Lambda]1,\[Lambda]2} // ColumnForm];
Print["{NbLegCoef1,NbLegCoef1n,period1,period1n,\[Epsilon]1,imax}=",{Length[LegendreCoef1],Length[LegendreCoef1n],period1,period1n,\[Epsilon]1,imax},"{NbLegCoef2,period2,period2n,\[Epsilon]2}=",{Length[LegendreCoef2],period2,period2n,\[Epsilon]2}]];
If[printflag==4|| MemberQ[printflag,4] ,Print[Table[Plot[SymetrizedBiHestonUnderlying1VanillaIntegrand[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2],{\[Omega]2,0 ,2period2},PlotPoints->50,PlotRange->All,PlotLabel->"1st Inverse Fourier: K ="<>ToString[K]<>" \[Omega]1="<>ToString[\[Omega]1]],{\[Omega]1,{0,0.2,2}}]]];
If[printflag==6|| MemberQ[printflag,6] ,Print[ListPlot[Table[{\[Omega]2,AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonUnderlying1VanillaIntegrand[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax][[2]]},{\[Omega]2,0,period2,period2/30}],Joined->True,PlotLabel->"2nd Inverse Fourier:",PlotRange->All]]];
res=AdaptativeIntegrate[Function[\[Omega]2,a=AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonUnderlying1VanillaIntegrand[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax];If[printflag==7|| MemberQ[printflag,7],Print["Integ_2=",a]];a[[2]]],LegendreCoef2,period2,period2n,\[Epsilon]2,imax];
If[printflag==7|| MemberQ[printflag,7],Print["Integ_1=",res]];
res[[2]]]


BiHestonUnderlying1VanillaAux2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=
2/(2\[Pi])^2 Module[{a,res,res2,Y={Log[S[[1]]],Log[S[[2]]]}},
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",S // ColumnForm," \[CapitalSigma]=",\[CapitalSigma] //MatrixForm,"M=",M//MatrixForm," \[CapitalSigma]inf=",\[CapitalSigma]inf//MatrixForm ," Q=",Q//MatrixForm ," \[Rho]=",\[Rho]//ColumnForm," Imaginary Shifts=",{\[Lambda]1,\[Lambda]2} // ColumnForm];
Print["{NbLegCoef1,NbLegCoef1n,period1,period1n,\[Epsilon]1,imax}=",{Length[LegendreCoef1],Length[LegendreCoef1n],period1,period1n,\[Epsilon]1,imax},"{NbLegCoef2,period2,period2n,\[Epsilon]2}=",{Length[LegendreCoef2],period2,period2n,\[Epsilon]2}]];
If[printflag==4|| MemberQ[printflag,4] ,Print[Table[Plot[SymetrizedBiHestonUnderlying1VanillaIntegrand2[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2],{\[Omega]2,0 ,2period2},PlotPoints->50,PlotRange->All,PlotLabel->"1st Inverse Fourier: K ="<>ToString[K]<>" \[Omega]1="<>ToString[\[Omega]1]],{\[Omega]1,{0,0.2,2}}]]];
If[printflag==6|| MemberQ[printflag,6] ,Print[ListPlot[Table[{\[Omega]2,AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonUnderlying1VanillaIntegrand2[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax][[2]]},{\[Omega]2,0,period2,period2/30}],Joined->True,PlotLabel->"2nd Inverse Fourier:"]]];
res=AdaptativeIntegrate[Function[\[Omega]2,a=AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonUnderlying1VanillaIntegrand2[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax];If[printflag==7|| MemberQ[printflag,7],Print["Integ_2=",a]];a[[2]]],LegendreCoef2,period2,period2n,\[Epsilon]2,imax];
If[printflag==7|| MemberQ[printflag,7],Print["Integ_1=",res]];
res[[2]]]


SymetrizedBiHestonUnderlying1VanillaIntegrand[Y_,K_,\[Tau]_,\[CapitalSigma]_,M_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,\[Omega]1_,\[Omega]2_]:=Module[{x1=Y[[1]],x2=Y[[2]],k1=(\[Omega]1+I \[Lambda]1),Sk1=(-\[Omega]1+I \[Lambda]1),k2= (\[Omega]2+I \[Lambda]2),Sk2= (-\[Omega]2+I \[Lambda]2),Sk1A=(-\[Omega]1+I \[Lambda]1),k1A=(\[Omega]1-I \[Lambda]1),k2A=(\[Omega]2-I \[Lambda]2),\[Alpha],\[Alpha]A,Sym\[Alpha],Sym\[Alpha]A,\[Alpha]2,\[Alpha]A2,Sym\[Alpha]2,Sym\[Alpha]A2,propagatorDroit,SympropagatorDroit,propagatorGauche,SympropagatorGauche,propagatorDroit2,SympropagatorDroit2,propagatorGauche2,SympropagatorGauche2},
Re[\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);
propagatorDroit=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta],\[Tau]];SympropagatorDroit=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta],\[Tau]];
propagatorGauche=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2A},\[Beta],\[Tau]];SympropagatorGauche=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta],\[Tau]];
\[Alpha] propagatorDroit FirstUnderlyingVanillaPayOffFourierDroite[k1,k2,K]+
Sym\[Alpha] SympropagatorDroit FirstUnderlyingVanillaPayOffFourierDroite[Sk1,k2,K]+
\[Alpha]A propagatorGauche FirstUnderlyingVanillaPayOffFourierGauche[k1,k2A,K]+
Sym\[Alpha]A SympropagatorGauche FirstUnderlyingVanillaPayOffFourierGauche[Sk1A,k2A,K]]]



SymetrizedBiHestonUnderlying1VanillaIntegrand2[Y_,K_,\[Tau]_,\[CapitalSigma]_,M_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,\[Omega]1_,\[Omega]2_]:=Module[{x1=Y[[1]],x2=Y[[2]],k1=(\[Omega]1+I \[Lambda]1),Sk1=(-\[Omega]1+I \[Lambda]1),k2= (\[Omega]2+I \[Lambda]2),Sk2= (-\[Omega]2+I \[Lambda]2),Sk1A=(-\[Omega]1+I \[Lambda]1),k1A=(\[Omega]1-I \[Lambda]1),k2A=(\[Omega]2-I \[Lambda]2),\[Alpha],\[Alpha]A,Sym\[Alpha],Sym\[Alpha]A,\[Alpha]2,\[Alpha]A2,Sym\[Alpha]2,Sym\[Alpha]A2,propagatorDroit,SympropagatorDroit,propagatorGauche,SympropagatorGauche,propagatorDroit2,SympropagatorDroit2,propagatorGauche2,SympropagatorGauche2},
Re[\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);
propagatorDroit=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta]m,\[Tau]];SympropagatorDroit=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta]m,\[Tau]];
propagatorGauche=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2A},\[Beta]m,\[Tau]];SympropagatorGauche=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta]m,\[Tau]];
\[Alpha] propagatorDroit FirstUnderlyingVanillaPayOffFourierDroite[k1,k2,K]+
Sym\[Alpha] SympropagatorDroit FirstUnderlyingVanillaPayOffFourierDroite[Sk1,k2,K]+
\[Alpha]A propagatorGauche FirstUnderlyingVanillaPayOffFourierGauche[k1,k2A,K]+
Sym\[Alpha]A SympropagatorGauche FirstUnderlyingVanillaPayOffFourierGauche[Sk1A,k2A,K]]]



FirstUnderlyingVanillaPayOffFourierDroite[k1_,k2_,K_]:=(I K^(1+I k1))/(I k1 k2-k1^2 k2)


FirstUnderlyingVanillaPayOffFourierGauche[k1_,k2_,K_]:=-(K^(1+I k1)/(k1 k2+I k1^2 k2))


BiHestonUnderlying2Vanilla[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,\[Beta]_,\[Rho]_,printflag_]:=Module[{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,LegendreCoef2,period2,period2n,\[Epsilon]2,imax,\[Lambda]1,\[Lambda]2,Q},
Q=CholeskyDecomposition[-((M.\[CapitalSigma]inf+\[CapitalSigma]inf. Transpose[M])/2)]/\[Beta];
{{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1},{LegendreCoef2,period2,period2n,\[Epsilon]2},imax,\[Lambda]1,\[Lambda]2}=BiHestonVanillaOptimalParameters[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],"Underlying2Option"];
BiHestonUnderlying2Vanilla[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag]
]


BiHestonUnderlying2Vanilla2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,printflag_]:=Module[{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,LegendreCoef2,period2,period2n,\[Epsilon]2,imax,\[Lambda]1,\[Lambda]2,\[Beta]m},
{{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1},{LegendreCoef2,period2,period2n,\[Epsilon]2},imax,\[Lambda]1,\[Lambda]2}=BiHestonVanillaOptimalParameters[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],"Underlying2Option"];
\[Beta]m=-((M.\[CapitalSigma]inf+\[CapitalSigma]inf.Transpose[M])/2).Inverse[(Transpose[Q].Q)];
BiHestonUnderlying2Vanilla2[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag]
]


BiHestonUnderlying2Vanilla[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=BiHestonUnderlying2VanillaAux[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag] /; K>=0


BiHestonUnderlying2Vanilla2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=BiHestonUnderlying2VanillaAux2[S,K,\[Tau],\[CapitalSigma],M,\[CapitalSigma]inf,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax},{LegendreCoef2,period2,period2n,\[Epsilon]2},printflag] /; K>=0


BiHestonUnderlying2VanillaAux[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=
2/(2\[Pi])^2 Module[{a,res,res2,Y={Log[S[[1]]],Log[S[[2]]]}},
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",S // ColumnForm," \[CapitalSigma]=",\[CapitalSigma] //MatrixForm,"M=",M//MatrixForm," \[CapitalSigma]inf=",\[CapitalSigma]inf//MatrixForm ," Q=",Q//MatrixForm ," \[Rho]=",\[Rho]//ColumnForm," Imaginary Shifts=",{\[Lambda]1,\[Lambda]2} // ColumnForm];
Print["{NbLegCoef1,NbLegCoef1n,period1,period1n,\[Epsilon]1,imax}=",{Length[LegendreCoef1],Length[LegendreCoef1n],period1,period1n,\[Epsilon]1,imax},"{NbLegCoef2,period2,period2n,\[Epsilon]2}=",{Length[LegendreCoef2],period2,period2n,\[Epsilon]2}]];
If[printflag==4|| MemberQ[printflag,4] ,Print[Table[Plot[SymetrizedBiHestonUnderlying2VanillaIntegrand[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2],{\[Omega]2,0 ,2period2},PlotPoints->50,PlotRange->All,PlotLabel->"1st Inverse Fourier: K ="<>ToString[K]<>" \[Omega]1="<>ToString[\[Omega]1]],{\[Omega]1,{0,0.2,2}}]]];
If[printflag==6|| MemberQ[printflag,6] ,Print[ListPlot[Table[{\[Omega]2,AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonUnderlying2VanillaIntegrand[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax][[2]]},{\[Omega]2,0,period2,period2/30}],Joined->True,PlotLabel->"2nd Inverse Fourier:",PlotRange->All]]];
res=AdaptativeIntegrate[Function[\[Omega]2,a=AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonUnderlying2VanillaIntegrand[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta],\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax];If[printflag==7|| MemberQ[printflag,7],Print["Integ_2=",a]];a[[2]]],LegendreCoef2,period2,period2n,\[Epsilon]2,imax];
If[printflag==7|| MemberQ[printflag,7],Print["Integ_1=",res]];
res[[2]]]


BiHestonUnderlying2VanillaAux2[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_},printflag_]:=
2/(2\[Pi])^2 Module[{a,res,res2,Y={Log[S[[1]]],Log[S[[2]]]}},
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",S // ColumnForm," \[CapitalSigma]=",\[CapitalSigma] //MatrixForm,"M=",M//MatrixForm," \[CapitalSigma]inf=",\[CapitalSigma]inf//MatrixForm ," Q=",Q//MatrixForm ," \[Rho]=",\[Rho]//ColumnForm," Imaginary Shifts=",{\[Lambda]1,\[Lambda]2} // ColumnForm];
Print["{NbLegCoef1,NbLegCoef1n,period1,period1n,\[Epsilon]1,imax}=",{Length[LegendreCoef1],Length[LegendreCoef1n],period1,period1n,\[Epsilon]1,imax},"{NbLegCoef2,period2,period2n,\[Epsilon]2}=",{Length[LegendreCoef2],period2,period2n,\[Epsilon]2}]];
If[printflag==4|| MemberQ[printflag,4] ,Print[Table[Plot[SymetrizedBiHestonUnderlying2VanillaIntegrand2[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2],{\[Omega]2,0 ,2period2},PlotPoints->50,PlotRange->All,PlotLabel->"1st Inverse Fourier: K ="<>ToString[K]<>" \[Omega]1="<>ToString[\[Omega]1]],{\[Omega]1,{0,0.2,2}}]]];
If[printflag==6|| MemberQ[printflag,6] ,Print[ListPlot[Table[{\[Omega]2,AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonUnderlying2VanillaIntegrand2[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax][[2]]},{\[Omega]2,0,period2,period2/30}],Joined->True,PlotLabel->"2nd Inverse Fourier:",PlotRange->All]]];
res=AdaptativeIntegrate[Function[\[Omega]2,a=AdaptativeIntegrate[Function[\[Omega]1,SymetrizedBiHestonUnderlying2VanillaIntegrand2[Y,K,\[Tau],\[CapitalSigma],M,Q,\[Rho],\[Beta]m,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax];If[printflag==7|| MemberQ[printflag,7],Print["Integ_2=",a]];a[[2]]],LegendreCoef2,period2,period2n,\[Epsilon]2,imax];
If[printflag==7|| MemberQ[printflag,7],Print["Integ_1=",res]];
res[[2]]]


SymetrizedBiHestonUnderlying2VanillaIntegrand[Y_,K_,\[Tau]_,\[CapitalSigma]_,M_,Q_,\[Rho]_,\[Beta]_,\[Lambda]1_,\[Lambda]2_,\[Omega]1_,\[Omega]2_]:=Module[{x1=Y[[1]],x2=Y[[2]],k1=(\[Omega]1+I \[Lambda]1),Sk1=(-\[Omega]1+I \[Lambda]1),k2= (\[Omega]2+I \[Lambda]2),Sk1A=(-\[Omega]1-I \[Lambda]1),k1A=(\[Omega]1-I \[Lambda]1),k2A=(\[Omega]2+I \[Lambda]2),\[Alpha],\[Alpha]A,Sym\[Alpha],Sym\[Alpha]A,\[Alpha]2,\[Alpha]A2,Sym\[Alpha]2,Sym\[Alpha]A2,propagatorDroit,SympropagatorDroit,propagatorGauche,SympropagatorGauche,propagatorDroit2,SympropagatorDroit2,propagatorGauche2,SympropagatorGauche2},
Re[\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1A-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);
propagatorDroit=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta],\[Tau]];SympropagatorDroit=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta],\[Tau]];
propagatorGauche=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I k1A,-I k2A},\[Beta],\[Tau]];SympropagatorGauche=BiHestonLaplaceQuickTransform[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta],\[Tau]];
\[Alpha] propagatorDroit SecondUnderlyingVanillaPayOffFourierDroite[k1,k2,K]+
Sym\[Alpha] SympropagatorDroit SecondUnderlyingVanillaPayOffFourierDroite[Sk1,k2,K]+
\[Alpha]A propagatorGauche SecondUnderlyingVanillaPayOffFourierGauche[k1A,k2A,K]+
Sym\[Alpha]A SympropagatorGauche SecondUnderlyingVanillaPayOffFourierGauche[Sk1A,k2A,K]]]



SymetrizedBiHestonUnderlying2VanillaIntegrand2[Y_,K_,\[Tau]_,\[CapitalSigma]_,M_,Q_,\[Rho]_,\[Beta]m_,\[Lambda]1_,\[Lambda]2_,\[Omega]1_,\[Omega]2_]:=Module[{x1=Y[[1]],x2=Y[[2]],k1=(\[Omega]1+I \[Lambda]1),Sk1=(-\[Omega]1+I \[Lambda]1),k2= (\[Omega]2+I \[Lambda]2),Sk1A=(-\[Omega]1-I \[Lambda]1),k1A=(\[Omega]1-I \[Lambda]1),k2A=(\[Omega]2+I \[Lambda]2),\[Alpha],\[Alpha]A,Sym\[Alpha],Sym\[Alpha]A,\[Alpha]2,\[Alpha]A2,Sym\[Alpha]2,Sym\[Alpha]A2,propagatorDroit,SympropagatorDroit,propagatorGauche,SympropagatorGauche,propagatorDroit2,SympropagatorDroit2,propagatorGauche2,SympropagatorGauche2},
Re[\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1A-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);
propagatorDroit=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I k1,-I k2},\[Beta]m,\[Tau]];SympropagatorDroit=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1,-I k2},\[Beta]m,\[Tau]];
propagatorGauche=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I k1A,-I k2A},\[Beta]m,\[Tau]];SympropagatorGauche=BiHestonLaplaceQuickTransform2[M,Q,\[Rho], \[CapitalSigma],{-I Sk1A,-I k2A},\[Beta]m,\[Tau]];
\[Alpha] propagatorDroit SecondUnderlyingVanillaPayOffFourierDroite[k1,k2,K]+
Sym\[Alpha] SympropagatorDroit SecondUnderlyingVanillaPayOffFourierDroite[Sk1,k2,K]+
\[Alpha]A propagatorGauche SecondUnderlyingVanillaPayOffFourierGauche[k1A,k2A,K]+
Sym\[Alpha]A SympropagatorGauche SecondUnderlyingVanillaPayOffFourierGauche[Sk1A,k2A,K]]]



SecondUnderlyingVanillaPayOffFourierDroite[k1_,k2_,K_]:=(I K^(1+I k2))/(I k1 k2-k2^2 k1)


SecondUnderlyingVanillaPayOffFourierGauche[k1_,k2_,K_]:=-(K^(1+I k2)/(k1 k2+I k2^2 k1))


IntegerConvert[x_,{x1_,n1_},{x2_,n2_},nmax_]:=Module[{ntheo=n1+Max[0,Floor[(x-x1)/(x2-x1) (n2-n1)]]},Min[ntheo,nmax]]


RealConvert[x_,{x1_,n1_},{x2_,n2_},nmax_]:=Module[{ntheo=n1+Max[0,(x-x1)/(x2-x1) (n2-n1)]},Min[ntheo,nmax]]


BiHestonVanillaOptimalParameters[S_,K_,\[Tau]_,\[CapitalSigma]_,M_,\[CapitalSigma]inf_,Q_,\[Rho]_,type_]:=Module[{\[Lambda]1,\[Lambda]2,scope1,scope2,Nb1,LegendreCoef1,Nb1n,LegendreCoef1n,period1,period1n,\[Epsilon]1,Nb2,LegendreCoef2,period2,period2n,\[Epsilon]2,imax,s1=S[[1]],s2=S[[2]],Rmax,smax,smin,forward=S[[1]]-S[[2]],scopeDivisor1=1,scopeDivisor1n=1,scopeDivisor2=1,scopeDivisor2n=1},
(* defaut parameters *)
scope1=3/Sqrt[(\[CapitalSigma][[1,1]]+\[CapitalSigma][[2,2]]+\[CapitalSigma]inf[[1,1]]+\[CapitalSigma]inf[[2,2]])/4 \[Tau]];scope2=4/Sqrt[(\[CapitalSigma][[1,1]]+\[CapitalSigma][[2,2]]+\[CapitalSigma]inf[[1,1]]+\[CapitalSigma]inf[[2,2]])/4 \[Tau]];
Nb1=12;Nb1n=8;Nb2=12;
period1=scope1;period1n=scope1;
period2=scope2;period2n=scope2/10;
(* non default *)
If[type=="VanillaSpreadoption",
smin=Min[s1,s2];smax=Max[s1,s2];
If[K!= 0,
Nb1=IntegerConvert[-Log[Abs[K]/smax],{1,12},{6,12},35];
Nb1n=IntegerConvert[-Log[Abs[K]/smax],{1,8},{6,8},35];
Nb2=IntegerConvert[-Log[Abs[K]/smax],{1,12},{6,12},35]];
Nb1=Max[Nb1,IntegerConvert[(smax-smin)/smax,{0.1,12},{0.9,30},35]];
Nb1n=Max[Nb1n,IntegerConvert[(smax-smin)/smax,{0.1,8},{0.9,20},35]];
Nb2=Max[Nb2,IntegerConvert[(smax-smin)/smax,{0.1,12},{0.9,30},35]];
If[K!=0,
scopeDivisor1=RealConvert[-Log[Abs[K]/smax],{1,1},{6,1},2];
scopeDivisor1n=RealConvert[-Log[Abs[K]/smax],{1,1},{6,1},2];
scopeDivisor2=RealConvert[-Log[Abs[K]/smax],{1,1},{6,1},2];
scopeDivisor2n=RealConvert[-Log[Abs[K]/smax],{1,1},{6,4},4]];
scopeDivisor1=Max[scopeDivisor1,RealConvert[(smax-smin)/smax,{0.1,1},{0.9,2},2]];
scopeDivisor1n=Max[scopeDivisor1n,RealConvert[(smax-smin)/smax,{0.1,1},{0.9,4},4]];
scopeDivisor2=Max[scopeDivisor2,RealConvert[(smax-smin)/smax,{0.1,1},{0.9,1},2]];
scopeDivisor2n=Max[scopeDivisor2n,RealConvert[(smax-smin)/smax,{0.1,1},{0.9,4},4]];
];
If[(type=="Underlying1Option")||(type=="Underlying2Option"),
scope1=3/Sqrt[(\[CapitalSigma][[1,1]]+\[CapitalSigma][[2,2]]+\[CapitalSigma]inf[[1,1]]+\[CapitalSigma]inf[[2,2]])/4 \[Tau]];scope2=4/Sqrt[(\[CapitalSigma][[1,1]]+\[CapitalSigma][[2,2]]+\[CapitalSigma]inf[[1,1]]+\[CapitalSigma]inf[[2,2]])/4 \[Tau]];
Nb1=30;Nb1n=20;Nb2=30;
period1=scope1;period1n=scope1;
period2=scope2;period2n=scope2/10;
];
period1 /=scopeDivisor1;period1n /=scopeDivisor1n;period2 /=scopeDivisor2;period2n /=scopeDivisor2n;
LegendreCoef1=LegendreCoeffs[Nb1];LegendreCoef1n=LegendreCoeffs[Nb1n];\[Epsilon]1=0.00001;
LegendreCoef2=LegendreCoeffs[Nb2];\[Epsilon]2=0.00001;imax=10;\[Lambda]1=1.1;\[Lambda]2=1.2;
{{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1},{LegendreCoef2,period2,period2n,\[Epsilon]2},imax,\[Lambda]1,\[Lambda]2}]



AdaptativeIntegrate[Func_,LegendreCoef0_,LegendreCoefn_,period0_,periodn_,\[Epsilon]_,imax_]:=Module[{sum=0.0,increment=\[Epsilon]+1,i=0},
sum=CoeffBasedIntegrate[Func,LegendreCoeffsFromLegendre[LegendreCoef0,0,period0]];
While[(Abs[increment]>\[Epsilon])&&(i<imax),increment=CoeffBasedIntegrate[Func,LegendreCoeffsFromLegendre[LegendreCoefn,period0+i*periodn,period0+(i+1)*periodn]];i+=1;sum+=increment];{i,sum}]


AdaptativeIntegrate[Func_,LegendreCoef0_,period0_,periodn_,\[Epsilon]_,imax_]:=Module[{sum=0.0,increment=\[Epsilon]+1,i=0},
sum=CoeffBasedIntegrate[Func,LegendreCoeffsFromLegendre[LegendreCoef0,0,period0]];
While[(Abs[increment]>\[Epsilon])&&(i<imax),increment=Func[period0+(i+1/2)*periodn]periodn;i+=1;sum+=increment];{i,sum}]


VectorAdaptativeIntegrate[Func_,LegendreCoef0_,LegendreCoefn_,period0_,periodn_,\[Epsilon]_,imax_,n_]:=Module[{sum=Table[0.0,{i,1,n}],increment=Table[\[Epsilon]+1,{i,1,n}],i=0},
sum=CoeffBasedIntegrate[Func,LegendreCoeffsFromLegendre[LegendreCoef0,0,period0]];
While[(Max[Abs[increment]]>\[Epsilon])&&(i<imax),increment=CoeffBasedIntegrate[Func,LegendreCoeffsFromLegendre[LegendreCoefn,period0+i*periodn,period0+(i+1)*periodn]];i+=1;sum+=increment];{i,sum}]


VectorAdaptativeIntegrate[Func_,LegendreCoef0_,period0_,periodn_,\[Epsilon]_,imax_,n_]:=Module[{sum=Table[0.0,{i,1,n}],increment=Table[\[Epsilon]+1,{i,1,n}],i=0},
sum=CoeffBasedIntegrate[Func,LegendreCoeffsFromLegendre[LegendreCoef0,0,period0]];
While[(Max[Abs[increment]]>\[Epsilon])&&(i<imax),increment=Func[period0+(i+1/2)*periodn]periodn;i+=1;sum+=increment];{i,sum}]


phi[x_]:=Exp[-x^2/2]/Sqrt[2Pi]


Nd[x_]:=(Erf[x/Sqrt[2]]+1)/2


LogNormalSpreadDigitaleCall[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=NIntegrate[phi[x]Nd[-(Log[(k+S2 E^(-1/2 sig2^2 t+sig2 Sqrt[t] x))/(S1 E^(-1/2 sig1^2 t))]-rho sig1 Sqrt[t] x)/(Sqrt[1-rho^2] sig1 Sqrt[t])],{x,-Infinity,-1,+Infinity}]


MesureQTLogNormalSpreadDigitale[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=LogNormalSpreadDigitaleCall[S1 ,S2 ,sig1,sig2,rho,k,t]


MesureQ1LogNormalSpreadDigitale[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=LogNormalSpreadDigitaleCall[S1 Exp[sig1^2 t],S2 Exp[rho sig1 sig2 t],sig1,sig2,rho,k,t]


MesureQ2LogNormalSpreadDigitale[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=LogNormalSpreadDigitaleCall[S1 Exp[rho sig1 sig2 t],S2 Exp[sig2^2 t],sig1,sig2,rho,k,t]


LogNormalSpreadOptionAux[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=S1 MesureQ1LogNormalSpreadDigitale[S1,S2,sig1,sig2,rho,k,t]-S2 MesureQ2LogNormalSpreadDigitale[S1,S2,sig1,sig2,rho,k,t]-k MesureQTLogNormalSpreadDigitale[S1,S2,sig1,sig2,rho,k,t]


LogNormalSpreadOption[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=LogNormalSpreadOptionAux[S1,S2,sig1,sig2,rho,k,t] /; k>=0


LogNormalSpreadOption[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=S1-S2-k+LogNormalSpreadOptionAux[S2,S1,sig2,sig1,rho,-k,t] /; k<0


MatrixLog2[{{a_,b_},{c_,d_}}]:=Module[{logdetm,adm,adp,logdetp,log4,P,InvP,det=Sqrt[a^2+4 b c-2 a d+d^2]},
adm=a+d-det;adp=a+d+det;
If[(Im[adm]==0)&&(Re[adm]<=0),logdetm=0,logdetm=Log[adm]];
If[(Im[adp]==0)&&(Re[adp]<=0),logdetp=0,logdetp=Log[adp]];
log4=Log[4];{{(-det log4+(-a+d+det) logdetm+(a-d+det) logdetp)/(2 det),(-b (logdetm-logdetp))/ det},{(c (-logdetm+logdetp))/det,(-det log4+(a-d+det) logdetm+(-a+d+det)logdetp)/(2 det)}}
]


TrMatrixLog2[{{a_,b_},{c_,d_}}]:=Module[{},
Log[- b c+a d]
]



