(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



InitialMarketData[BondYTM["TBond 4.95 2010"]]=0.0705;
InitialMarketData[BondDateList["TBond 4.95 2010"]]=
		{0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5,13.5,14.5};
InitialMarketData[BondNotionelQ["TBond 4.95 2010"]]=True;
InitialMarketData[BondConversionFactor["TBond 4.95 2010"]]=1.1;
InitialMarketData[BondCoupon["TBond 4.95 2010"]]=0.0495;
InitialMarketData[BondFaceVaalue["TBond 4.95 2010"]]=1000000;
InitialMarketData[BondCurrency["TBond 4.95 2010"]]=usd;



InitialMarketData[BondYTM["TBond 4.65 2013"]]=0.0711;
InitialMarketData[BondDateList["TBond 4.65 2013"]]=
		{0.1,1.1,2.1,3.1,4.1,5.1,6.1,7.1,8.1,9.1,10.1,11.1,12.1,13.1,14.1,15.1,16.1,17.1};
InitialMarketData[BondNotionelQ["TBond 4.65 2013"]]=True;
InitialMarketData[BondConversionFactor["TBond 4.95 2010"]]=1.1;
InitialMarketData[BondCoupon["TBond 4.65 2013"]]=0.0465;
InitialMarketData[BondFaceVaalue["TBond 4.65 2013"]]=1000000;
InitialMarketData[BondCurrency["TBond 4.65 2013"]]=usd;



InitialMarketData[BondYTM["TBond 3.95 2008"]]=0.0701;
InitialMarketData[BondDateList["TBond 3.95 2008"]]=
		{0.7,1.7,2.7,3.7,4.7,5.7,6.7,7.7,8.7,9.7,10.7,11.7,12.7};
InitialMarketData[BondNotionelQ["TBond 3.95 2008"]]=True;
InitialMarketData[BondConversionFactor["TBond 4.95 2010"]]=1.1;
InitialMarketData[BondCoupon["TBond 3.95 2008"]]=0.0495;
InitialMarketData[BondFaceVaalue["TBond 3.95 2008"]]=1000000;
InitialMarketData[BondCurrency["TBond 3.95 2008"]]=usd;



InitialMarketData[NotionelList[usd]]={"TBond 4.95 2010","TBond 4.65 2013","TBond 3.95 2008"};
