(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



InitialMarketData[StockPrice["IBM"]]=11.43;
InitialMarketData[StockForwardDiscount[t_,"IBM"]]:=
		StockForwardDiscountFromDividend[t,0.015];
InitialMarketData[StockBeta["IBM"]]=0.99;
InitialMarketData[StockNDPVolatility["IBM"]]=0.13;
InitialMarketData[StockCurrency["IBM"]]=Currency[usd];


InitialMarketData[StockPrice["DEC"]]=7.43;
InitialMarketData[StockForwardDiscount[t,"DEC"]]:=
		StockForwardDiscountFromDividend[t_,0.012];
InitialMarketData[StockBeta["DEC"]]=0.98;
InitialMarketData[StockNDPVolatility["DEC"]]=0.12;
InitialMarketData[StockCurrency["DEC"]]=Currency[usd];


InitialMarketData[StockPrice["Michelin"]]=3427.46;
InitialMarketData[StockForwardDiscount[t,"Michelin"]]:=
		StockForwardDiscountFromDividend[t_,0.024];
InitialMarketData[StockBeta["Michelin"]]=0.98;
InitialMarketData[StockNDPVolatility["Michelin"]]=0.09;
InitialMarketData[StockCurrency["Michelin"]]=Currency[frf];


InitialMarketData[StockPrice["Carrefour"]]=2907.73;
InitialMarketData[StockForwardDiscount[t,"Carrefour"]]:=
		StockForwardDiscountFromDividend[t_,0.026];
InitialMarketData[StockBeta["Carrefour"]]=1.1;
InitialMarketData[StockNDPVolatility["Carrefour"]]=0.12;
InitialMarketData[StockCurrency["Carrefour"]]=Currency[frf];


StockForwardDiscountFromDividend[t_,d_]:=Exp[ - t d]
